spring:
  profiles:
    include: secret
  application:
    name: find_restaurant

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

white-list:
  paths:
    - "/swagger-ui.html"
    - "/swagger-ui/**"
    - "/v3/api-docs/**"
    - "/swagger-resources/**"
    - "/webjars/**"
    - "/reissue"
    - "/user/signup/**"
    - "/"
    - "/actuator/**"
#    - "/image/**"