spring:
  profiles:
    include: secret
  application:
    name: find_restaurant

white-list:
  paths:
    - "/swagger-ui.html"
    - "/swagger-ui/**"
    - "/v3/api-docs/**"
    - "/swagger-resources/**"
    - "/webjars/**"
    - "/reissue"
    - "/user/signup/**"
    - "/"
    - "/actuator/**"
    - "/image/**"
