spring:
datasource:
  url: jdbc:h2:mem:testdb
  driver-class-name: org.h2.Driver
  usernickname: sa
  password:
  #    url: jdbc:mysql://43.201.10.254:3306/find_restaurant?autoReconnect=true
  #    username: root
  #    password: geojeeatsdskodb
  dbcp2: # 일정 시간마다 커넥션을 검사하여 유효하지 않은 커넥션을 제거
    test-on-borrow: true
    validation-query: SELECT 1
#    driver-class-name: org.h2.Driver
#    usernickname: sa
#    password:

jpa:
  hibernate:
    ddl-auto: create-drop
  show-sql: true
  defer-datasource-initialization: true  # ★ data.sql을 Hibernate 스키마 생성 이후로 지연
  properties:
    hibernate:
      #        dialect: org.hibernate.dialect.MySQLDialect
      dialect: org.hibernate.dialect.H2Dialect
      format_sql: true
      #        show_sql: true
      database-platform: org.hibernate.dialect.H2Dialect
#    database-platform: org.hibernate.dialect.MySQLDialect
sql:
  init:
    mode: always

servlet:
  multipart:
    max-file-size: 30MB #업로드할 수 있는 개별 파일의 최대 크기. 기본 1MB
    max-request-size: 30MB

jwt:
  secret: eyJhbGciOiJIUzI1NiJ9eyJjYXRlZ29yeSI6InJlZnJlc2giLCJ1c2VybmFtZSI6InVzZXJAZXhhbXBsZS5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiaWF0IjoxNzU3Mjg5MDA1LCJleHAiOjE3NTg0OTg2MDV9hoQEMOnInETXrAHtNKoQqXdJOkI8qtmC2tKyaPxux0
  access-expiration-minutes: 1440 # 1일
  refresh-expiration-days: 14
  refresh-cookie-name: refresh_token
  access-header-name: Authorization

white-list:
  paths:
    - "/swagger-ui.html"            # Swagger UI 관련 HTML 페이지
    - "/swagger-ui/**"              # Swagger UI 관련 정적 리소스
    - "/v3/api-docs/**"             # Swagger UI 관련 API 문서
    - "/swagger-resources/**"       # Swagger UI 관련 리소스
    - "/webjars/**"                 # Swagger UI 관련 웹 자원
    - "/api/auth/**"                # 토큰 재발급, node js 인증
    - "/api/user/**"           # 사용자 정보 조회
    - "/api/signup"                 #회원가입
    - "/api/signup/**"              #회원가입 - 기타
    - "/api/login"                  #로그인
    - "/actuator/**"                # kubernetes 헬스 체크
    - "/api/check/**"               # 중복 체크
    - "/spring/security"            # node js 을 위한 인증 확인용 엔드포인트